name: Test DNS Zones
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: stackexchange/dnscontrol
    steps:
    - uses: actions/checkout@v2
    - name: Test validity of dnsconfig.js
      run: |
        dnscontrol check
    - name: Preview changes against live DNS
      id: dnscontrol_preview
      env:
        MYTHIC_API_KEY_ID: ${{ secrets.MYTHIC_API_KEY_ID }}
        MYTHIC_API_KEY_SECRET: ${{ secrets.MYTHIC_API_KEY_SECRET }}
      run: |
        dnscontrol preview
    - name: Preview pull request comment
      uses: unsplash/comment-on-pr@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
        check_for_duplicate_msg: true